spring.application.name=briefcase


# DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/briefcase
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA / HIBERNATE
#spring.jpa.hibernate.ddl-auto=
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=principal

# POSTGRESQL DIALECT
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# CLOUDINARY
cloudinary.cloud_name=dlasxwxmj
cloudinary.api_key=529946834767619
cloudinary.api_secret=A_eZKOqHSlGWiTq5zF-0OpPJa9s